"""Sanitized quantitative research and portfolio engineering demos."""

from quant_portfolio.allocator import PortfolioSnapshot, allocate
from quant_portfolio.cross_asset import (
    CrossAssetConstraints,
    CrossAssetInput,
    CrossAssetOptimizationResult,
    OptimizationFailure,
    PITFixedPoint,
    PITMarketSnapshot,
    TargetPortfolio,
    optimize_cross_asset,
    target_to_order_intents,
)
from quant_portfolio.evaluation import (
    DeflatedSharpe,
    OverfitResult,
    SimulationResult,
    cpcv_splits,
    deflated_sharpe_ratio,
    probability_of_backtest_overfitting,
    simulate_market,
)
from quant_portfolio.methods import (
    black_litterman_expected_returns,
    constant_correlation_covariance,
    equal_risk_contribution_weights,
    ewma_covariance,
    factor_model_covariance,
    hierarchical_risk_parity_weights,
    ic_vol_expected_returns,
    ledoit_wolf_covariance,
    oas_covariance,
    random_matrix_covariance,
)
from quant_portfolio.objectives import (
    allocate_integer_lots,
    conditional_drawdown_at_risk,
    entropic_value_at_risk,
    maximum_drawdown,
    optimize_cdar,
    optimize_evar,
    optimize_max_diversification,
    optimize_max_sharpe,
)
from quant_portfolio.optimization import (
    MultiPeriodResult,
    OptimizationConstraints,
    OptimizationResult,
    estimate_capacity,
    estimate_covariance,
    optimize_cvar,
    optimize_mean_variance,
    optimize_multiperiod,
    research_allocation_weights,
    square_root_impact_cost,
    validate_research_allocation,
)
from quant_portfolio.synthetic_spread import (
    BacktestMetrics,
    SyntheticSpreadConfig,
    backtest_synthetic_spread,
    generate_synthetic_pair,
)

__all__ = [
    "BacktestMetrics",
    "CrossAssetConstraints",
    "CrossAssetInput",
    "CrossAssetOptimizationResult",
    "DeflatedSharpe",
    "MultiPeriodResult",
    "OptimizationConstraints",
    "OptimizationFailure",
    "OptimizationResult",
    "OverfitResult",
    "PITFixedPoint",
    "PITMarketSnapshot",
    "PortfolioSnapshot",
    "SimulationResult",
    "SyntheticSpreadConfig",
    "TargetPortfolio",
    "allocate",
    "allocate_integer_lots",
    "backtest_synthetic_spread",
    "black_litterman_expected_returns",
    "conditional_drawdown_at_risk",
    "constant_correlation_covariance",
    "cpcv_splits",
    "deflated_sharpe_ratio",
    "entropic_value_at_risk",
    "equal_risk_contribution_weights",
    "estimate_capacity",
    "estimate_covariance",
    "ewma_covariance",
    "factor_model_covariance",
    "generate_synthetic_pair",
    "hierarchical_risk_parity_weights",
    "ic_vol_expected_returns",
    "ledoit_wolf_covariance",
    "maximum_drawdown",
    "oas_covariance",
    "optimize_cdar",
    "optimize_cross_asset",
    "optimize_cvar",
    "optimize_evar",
    "optimize_max_diversification",
    "optimize_max_sharpe",
    "optimize_mean_variance",
    "optimize_multiperiod",
    "probability_of_backtest_overfitting",
    "random_matrix_covariance",
    "research_allocation_weights",
    "simulate_market",
    "square_root_impact_cost",
    "target_to_order_intents",
    "validate_research_allocation",
]
