"""Sanitized quantitative research and portfolio engineering demos."""

from quant_portfolio.allocator import PortfolioSnapshot, allocate
from quant_portfolio.cross_asset import (
    CrossAssetConstraints,
    CrossAssetInput,
    CrossAssetOptimizationResult,
    OptimizationFailure,
    PITFixedPoint,
    PITMarketSnapshot,
    TargetPortfolio,
    optimize_cross_asset,
    target_to_order_intents,
)
from quant_portfolio.methods import (
    black_litterman_expected_returns,
    equal_risk_contribution_weights,
    factor_model_covariance,
    hierarchical_risk_parity_weights,
    ic_vol_expected_returns,
    ledoit_wolf_covariance,
)
from quant_portfolio.optimization import (
    MultiPeriodResult,
    OptimizationConstraints,
    OptimizationResult,
    estimate_capacity,
    estimate_covariance,
    optimize_cvar,
    optimize_mean_variance,
    optimize_multiperiod,
    research_allocation_weights,
    square_root_impact_cost,
    validate_research_allocation,
)
from quant_portfolio.synthetic_spread import (
    BacktestMetrics,
    SyntheticSpreadConfig,
    backtest_synthetic_spread,
    generate_synthetic_pair,
)

__all__ = [
    "BacktestMetrics",
    "CrossAssetConstraints",
    "CrossAssetInput",
    "CrossAssetOptimizationResult",
    "MultiPeriodResult",
    "OptimizationConstraints",
    "OptimizationFailure",
    "OptimizationResult",
    "PITFixedPoint",
    "PITMarketSnapshot",
    "PortfolioSnapshot",
    "SyntheticSpreadConfig",
    "TargetPortfolio",
    "allocate",
    "backtest_synthetic_spread",
    "black_litterman_expected_returns",
    "equal_risk_contribution_weights",
    "estimate_capacity",
    "estimate_covariance",
    "factor_model_covariance",
    "generate_synthetic_pair",
    "hierarchical_risk_parity_weights",
    "ic_vol_expected_returns",
    "ledoit_wolf_covariance",
    "optimize_cross_asset",
    "optimize_cvar",
    "optimize_mean_variance",
    "optimize_multiperiod",
    "research_allocation_weights",
    "square_root_impact_cost",
    "target_to_order_intents",
    "validate_research_allocation",
]
